### ISSUE TITLE
When installing with Docker, is there a way to pass host information to an external PVE as an environment variable?

### ISSUE THREAD

**Issue by bumworld** [prometheus-pve/prometheus-pve-exporter#267]
When installing with Docker, I want to be able to call the API from an external Docker server without configuring PVE locally.
PVE_HOST: "https://192.168.0.112:8006" Even if I do this, the host information looks at localhost. 
I wonder if there is a way to install only node_exporter in PVE and install prometheus-pve-exporter externally using docker.

**Comment by znerol** [comment]
From the README:

> Visit http://localhost:9221/pve?target=1.2.3.4&cluster=1&node=1 where 1.2.3.4 is the IP of the Proxmox VE node to get metrics from. Specify the module request parameter, to choose which module to use from the config file.

hence, please point the `target` argument towards your PVE host. Also please take note of the example configurations at the bottom of the `README`. Especially take a look at _Example config for PVE exporter running on Prometheus host_. This example shows how to use relabelling in order to populate the `target` argument when scraping.
