### ISSUE TITLE
Dockerhub image?

### ISSUE THREAD

**Issue by oxivanisher** [prometheus-pve/prometheus-pve-exporter#32]
Hi there

There is already a image of this on dockerhub, but it does not get updated anymore. It would be pretty easy to just take the same [dockerfile ](https://hub.docker.com/r/jkroepke/prometheus-pve-exporter/dockerfile) and do automatic image building with push to dockerhub. What are your thoughts on this? I could help you set that up, if you would like to.
The existing but outdated image is located here: https://hub.docker.com/r/jkroepke/prometheus-pve-exporter

**Comment by znerol** [comment]
There have been at least two attempts to include a Dockerfile (see open pull requests). In the meantime I started to maintain docker images myself for another project, thus I am getting less opposed to that idea.

It looks like [prom/prometheus](https://github.com/prometheus/prometheus/blob/master/Dockerfile) ships with an example config and expects that people are either building their own docker images (with that one as a basis) or do a volume mount for `/etc/prometheus/prometheus.yml`.

I like this approach, since that puts the users in charge of supplying the config and it avoids an `entrypoint` script which needs to cater for every possible combination of configuration values.

**Comment by oxivanisher** [comment]
Yes, I like that too. I am currently using exactly this (only for private, internal monitoring) and it was really easy to get started with prometheus this way. Mounting the configs from "outside" is IMHO a really great solution.

**Comment by znerol** [comment]
Please take a look at #38. I haven't published an image with the `latest` tag, but you can test one of the `travis-build-` tags. E.g.:

    docker run -v /path/to/pve.yml:/etc/pve.yml -p 127.0.0.1:9221:9221 -it --rm prompve/prometheus-pve-exporter:travis-build-704258471

@oxivanisher what do you think?

**Comment by oxivanisher** [comment]
@znerol beautiful! it seems to work exactly like I expected it.

Some swiss german: Merci füu mou ;) Ig gloube mir kenne üs nämlech, weiss aber nümme vo wo. Hadi aume im Jabber gha AFAIK.

**Comment by znerol** [comment]
> Merci füu mou

Bitte gärn gscheh :cake:

**Comment by znerol** [comment]
Docker images with `latest` tag are now built and published automatically whenever I push a new tag :tada:
