### ISSUE TITLE
Is it correct argument handling? 

### ISSUE THREAD

**Issue by Alexqq11** [prometheus-pve/prometheus-pve-exporter#51]
https://github.com/prometheus-pve/prometheus-pve-exporter/blob/26a9623142ab9395f806139c29185d69755857d3/src/pve_exporter/cli.py#L26

**Comment by znerol** [comment]
That indeed looks totally wrong. The fun thing is that argument parsing still works. This is because `args` is always `None` and as a consequence the call boils down to essentially `parser.parse_args(None)`. And that in turn tells [parse_args](https://docs.python.org/3.9/library/argparse.html?#argparse.ArgumentParser.parse_args) to take what it needs from `sys.argv`.

:joy:

**Comment by Alexqq11** [comment]
))))
