### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by crysis-ps** [prometheus-pve/prometheus-pve-exporter#58]
Hello,
since v 1.2+ version I see the performance drop with loading metrics page.
I have the proxmox cluster with multiple nodes and ~500 VMs.
The metrics page has near 7000 lines.

The 1.1.2 version of pve exporter - the metrics page loads for ~400ms
The 1.2 or v2.0.3 version - the metrics page loads for ~7s

![image](https://user-images.githubusercontent.com/21262201/104890677-f1a8f580-5980-11eb-9bed-58b80d2e8162.png)
![image](https://user-images.githubusercontent.com/21262201/104890747-0a191000-5981-11eb-86c7-df4c98952d99.png)

**Comment by znerol** [comment]
There is only one code change [between 1.1.2 and 1.2.0](/prometheus-pve/prometheus-pve-exporter/compare/v1.1.2...v1.2.0): PR #22

The change indeed has potential to slow down scraping on big clusters, since it loops over every guest and fetches the config for each of them which will result in many API calls.

You could remove [this line](https://github.com/prometheus-pve/prometheus-pve-exporter/blob/71357f0f7d355b139447a2a93cddcc06d2f52926/src/pve_exporter/collector.py#L297) near the end of `collector.py`:

```python
    registry.register(ClusterNodeConfigCollector(pve))
```

Then check whether the problem goes away. The only purpose of this collector (as of now) is to extract the `onboot` flag.

**Comment by crysis-ps** [comment]
thank you.
yes, if this line is commented out - the metrics page loads for 300-400ms.

**Comment by znerol** [comment]
Ok, thanks for checking. So the best thing would be to make this configurable.

**Comment by znerol** [comment]
Published version `2.1.0` to dockerhub and pipy which includes #62. It is now possible to run `pve_exporter` with the `--no-collector.config` flag which will deactivate the slow collector.
